### ISSUE TITLE
Better outline "goal" of this tool

### ISSUE THREAD

**Issue by bnvk** [glennjones/note-editor#2]
Hey Glenn. Sounds promising. I'm curious to know more about what you're making here. Is it something along the lines of what [Pattern Lab](http://patternlab.io) would classify as "molecule" something like [Comment Form](http://demo.patternlab.io/?p=molecules-comment-form) but for IndieWeb interfaces regarding publishing of notes?

**Comment by glennjones** [comment]
Yes it’s a component for adding to IndieWeb interfaces for publishing of notes/status updates etc. It is what I use in my transmat backend for status updates. I am still working on a couple of issue, but I have outlined the features in the readme. Been based on a contenteditable element there are the usual small underlining issue, but people may find it useful

I have updated readme with feature list, hopefully upload the finished project in next few days

**Comment by bnvk** [comment]
@glennjones cool thanks, I look forward to checking it out :)
